source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'OpinionzRate_Example', :exclusive => true do
  pod "OpinionzRate", :path => "../"
end

target 'OpinionzRate_Tests', :exclusive => true do
  pod "OpinionzRate", :path => "../"

  
end
