source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/Opinionz/OPZPodSpecs.git'
#use_frameworks!

target 'OpinionzRate_Example', :exclusive => true do
  pod "OpinionzRate", :path => "../"
end

target 'OpinionzRate_Tests', :exclusive => true do
  pod "OpinionzRate", :path => "../"

  
end
